### ISSUE TITLE
[v19.26.5-3.0.3] home not loading right

### ISSUE THREAD

**Issue by zombieslayer1994** [qnblackcat/uYouPlus#1528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I have read the FAQ

### Device information

- iOS/iPadOS version: 17.5.1
- Device model: iPhone 13
- Sideload tool (AltStore, Sideloadly, TrollStore, etc.): signulous

### Describe the issue

When u click on home it stays blank when I scroll down some videos show up 
![IMG_8665](https://github.com/user-attachments/assets/3f28f829-5723-454b-84e9-47de100e5d26)
![IMG_8666](https://github.com/user-attachments/assets/a7691b62-c7b7-470b-98e2-228f9191fa1d)
![IMG_8667](https://github.com/user-attachments/assets/a0f0a084-b22a-48c2-8e79-e766b9485649)

### Steps to reproduce

1. Click on home 
2. Scroll down

### Are you using the latest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus

### Does the issue happen with the official YouTube app from the App Store?

❌ No, I cannot reproduce this issue in the official YouTube app from the App Store

**Comment by Jeromejj2** [comment]
How can you fix this?

**Comment by PoomSmart** [comment]
Fixed in the latest commit.

**Comment by rursache** [comment]
> @PoomSmart Fixed in the latest commit.

still happening to me on ipad, youtube v19.23.3, ipa build just now

![screenshot](https://i.imgur.com/iS4kLqQ.png)
