### ISSUE TITLE
[Bug] The app crashes when opening any video.

### ISSUE THREAD

**Issue by dfmcvn** [qnblackcat/uYouPlus#415]
### Device info
- iOS/iPadOS version: 15.6.1
- Device model: A2484
- Sideload tool (Ex: AltStore, Sideloadly...): Sideloadly
- Version of uYouPlus: [v17.33.2-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.33.2-2.1) and [v17.31.4-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.31.4-2.1)

### Describe the bug
The app crashes when opening any video.

### How to reproduce the bug
Sideload any version later than [v17.26.2-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.26.2-2.1).
Open the app and login into your account.
Close the app, reopen it and play any video.

### Does the issue happen with the official YouTube from AppStore?
No.

### Additional context: 
(none)

**Comment by dfmcvn** [comment]
#414

**Comment by qnblackcat** [comment]
Where is the crash log?
(The crash log can be found in the Settings app - Privacy - Analytics & Improvements - Analytics Data - Youtube...)

**Comment by dfmcvn** [comment]
#414 @iamcarron Can you help me to get the crash log of yours?
For some reasons I don't have access to my device right now. Ty!

**Comment by IamCarron** [comment]
Hi! I don’t have the option to output any log. I’m currently using the [17.26.2-2.1]

**Comment by dfmcvn** [comment]
Hi Carron,

You can go to Settings - Privacy - Analytics & Improvements - Analytics Data, then search for "youtube...".
It would have the crash timestamp already included in the filename.
Open the file, press the Share button - Save to File then upload that file to any cloud storage service (Drive for example).

**Comment by IamCarron** [comment]
Hi. I have just updated the app to the latest version but for some reason it doesn’t give me the option to out put any log. I just don’t have any Analytics & Improvements - Analytics Data under privacy.

**Comment by dfmcvn** [comment]
Hi Carron,

Perhaps you have trouble finding the log file. Here is a guide how to find it. (Apps will generate a log everytime it crashes.)

> ![8DBB6C86-2E6B-47F0-8C4E-B0C9B7F562D3](https://user-images.githubusercontent.com/22710598/187199356-e8b5b114-1562-4b39-99f5-e7c2a8730fdc.jpeg)

> ![C5CCA84C-D166-4F87-80CC-16A0758A566C](https://user-images.githubusercontent.com/22710598/187199375-54ed09fa-f137-4db8-94f3-2c69904c786f.jpeg)

> ![209C2F9C-8EAB-4BFF-82DC-4986B6D4F363](https://user-images.githubusercontent.com/22710598/187199385-4badbb8a-cade-4d3c-958c-e7fa20ac8e5d.jpeg)

**Comment by dfmcvn** [comment]
> For some reasons I don't have access to my iOS device right now.

If you are still unable to find your crash log, please tell me so I can temporarily close this issue until I have my iOS device, to reproduce the bug again. Ty!

**Comment by IamCarron** [comment]
Oh ok mb. I thought it was on uYou app not on settings, but for some reason the crash didn’t generated me any crash log.

**Comment by dfmcvn** [comment]
When you relaunch the app, does it show something like "`YouTube unexpectedly closed...`"?

I do see the log file when the app crashes on my device, but I don't have my device right now so I can't assist any further.

**Comment by IamCarron** [comment]
No for me it's juts crashing all the time but dont give me any message it just open like normal.

**Comment by han9over** [comment]
Yeah for me also it just crashes. No logs

**Comment by han9over** [comment]
Video playback is fine on 26.2. Short still crash on iPhone 12 Pro and xs latest ios

**Comment by jackhinkle** [comment]
This bug finally ticked me off enough to write about it.

iPhone 11, iOS 16 PB6 (20a5358a)
uYouPlus v17.34.3-2.1, installed via IPA to AltStore

App crashes immediately after opening a video sometimes. It seems to do this on its own schedule. One time I could open YouTube and it'll play just fine, but another time I'll open YouTube and it immediately crashes when I open a video. Every time I try clearing the app from ram, switching accounts, etc. No dice. Even after repeatedly tapping videos, crashing, and reopening the app.

After crashing, it says "Sorry, YouTube quit unexpectedly last time" with a "resume watching" button.

Attaching some .ips files from Analytics.
[IPS files.zip](https://github.com/qnblackcat/uYouPlus/files/9483666/IPS.files.zip)
[YouTube-2022-09-03-214342.txt](https://github.com/qnblackcat/uYouPlus/files/9483667/YouTube-2022-09-03-214342.txt)
[YouTube-2022-09-03-214400.txt](https://github.com/qnblackcat/uYouPlus/files/9483668/YouTube-2022-09-03-214400.txt)

**Comment by PoomSmart** [comment]
@jackhinkle Extracted from your crash log this might have something to do with Return YouTube Dislikes, I will check.

```
Last Exception Backtrace:
0   CoreFoundation                	       0x1b10ce248 __exceptionPreprocess + 164
1   libobjc.A.dylib               	       0x1aa4e7a68 objc_exception_throw + 60
2   CoreFoundation                	       0x1b123a338 -[NSException init] + 0
3   Foundation                    	       0x1abacb8a8 -[NSObject(NSKeyValueCoding) valueForUndefinedKey:] + 192
4   Foundation                    	       0x1ab564c54 -[NSObject(NSKeyValueCoding) valueForKey:] + 316
5   YouTubeDislikesReturn.dylib   	       0x10627e020 0x106278000 + 24608
6   UIKitCore                     	       0x1b3327298 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 700
7   UIKitCore                     	       0x1b426e87c -[UIView _postMovedFromSuperview:] + 652
8   UIKitCore                     	       0x1b3271c14 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1904
```

**Comment by risingkazuya05** [comment]
> ### Device info
> * iOS/iPadOS version: 15.1.1
> * Device model: A2484
> * Sideload tool (Ex: AltStore, Sideloadly...): AltStore, Signulous, TrollStore installer
> * Version of uYouPlus: [v17.34.3-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.34.3-2.1) [v17.33.2-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.33.2-2.1) and [v17.31.4-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.31.4-2.1)
> 
> ### Describe the bug
> The app crashes when opening any video after initial setup, basically once app is exited either manually or crashes, any video played after will crash right away.
> 
> ### How to reproduce the bug
> Sideload any version later than [v17.26.2-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.26.2-2.1). Open the app and login into your account. Close the app, reopen it and play any video.
> 
> ### Does the issue happen with the official YouTube from AppStore?
> No.
> 
> ### Additional context:
> Attaching some logs here 
[uYou_Crashlogs.zip](https://github.com/qnblackcat/uYouPlus/files/9485399/uYou_Crashlogs.zip)

**Comment by level3tjg** [comment]
@dfmcvn were you able to get crash logs from your device?

**Comment by Copperearth** [comment]
### Device info
- iOS/iPadOS version: 15.1.1
- Device model: iPhone X
- Sideload tool: Altstore
- Version of uYouPlus: v17.34.3-2.1

### Describe the bug
App crash when attempting to view video

### How to reproduce the bug
Simply tap on any video to crash your uyou+ enchanced youtube.
https://streamable.com/q0jhkv

### Crash log (if possible)
No crashlog can be found.

### Does the issue happen with the official YouTube from AppStore?
no

### Additional context:

**Comment by getBoolean** [comment]
I am encountering the same issue. Weirdly it was working at first after I sideloaded it but now it is having this issue

iPhone 13 mini, iOS 15.5
uYouPlus v17.34.3-2.1
Sideloaded with AltStore

[YouTube-2022-09-05-225652.txt](https://github.com/qnblackcat/uYouPlus/files/9493206/YouTube-2022-09-05-225652.txt)

**Comment by Guli-vali** [comment]
same

**Comment by neverExisted** [comment]
it just started happening to me. latest stable ios version. barely touched the settings so i'm not sure what's going on.

**Comment by neverExisted** [comment]
> it just started happening to me. latest stable ios version. barely touched the settings so i'm not sure what's going on.

also using the latest release of uYouplus

**Comment by leshniak** [comment]
Same story for me, on AltStore and Sideloadly.

**Comment by aaronliu0130** [comment]
[YouTube-2022-09-06-210432.zip](https://github.com/qnblackcat/uYouPlus/files/9501831/YouTube-2022-09-06-210432.zip)

**Comment by Deagan** [comment]
App crashing on video load for me too, regardless of VP9 on/off.

**Comment by slaynsubaki** [comment]
Hey guys, I managed to fix this issue by enabling "Fake Youtube Version" under YouPiP setting.

![image](https://user-images.githubusercontent.com/48038722/188792824-eba9c73d-a419-44a2-bbae-45d60ea5ed5e.png)

**Comment by leshniak** [comment]
@slaynsubaki works for me!

**Comment by scgames83** [comment]
@slaynsubaki Weirdly the app is still crashing for me even with Fake YouTube Version on. Do you think there is another setting that is causing or can fix it (I do have VP9 off)?

**Comment by scgames83** [comment]
It's still happening for me even on this version, with no settings touched. I did notice something weird. When I first installed it everything worked (Which was previously reported). Then I quickly closed and reopened the app and it was still working, but it still defaulted to light mode even with my phone's dark mode on. I then applied all the settings I normally had on and after that relaunch is when the app started to crash again. I deleted and reinstalled the app to test it without changing any settings, where the same thing happened after I relaunched the app. What I noticed though is by default when you install the IPA is that the dark mode is a single toggle, only allowing for it to be on or off. But after a relaunch, I got the in-app notification that YouTube was using my preferred default theme based off of phone settings which is when the app began to crash. As I previously mentioned, when I first installed the IPA and relaunched it, it still worked but never showed the notification. My theory is that when the notification shows up, some in-app update has been applied which must have something making the app crash. I know this is kind of a stretch, but I'm not knowledgable with this kind of stuff so this is all I can really think of. 
![IMG_3042](https://user-images.githubusercontent.com/32241975/188932683-cf515a75-50f9-40c4-bf44-9af6d85a0ec3.jpg)

**Comment by PoomSmart** [comment]
@scgames83 That dark mode thing is apparently normal and could even happen in a vanilla YouTube.

As for app crash, can you get the crash log?

**Comment by scgames83** [comment]
@PoomSmart 
[YouTube-2022-09-07-123107.ips.zip](https://github.com/qnblackcat/uYouPlus/files/9508226/YouTube-2022-09-07-123107.ips.zip)
I have no idea what settings were turned on or off when this log was made but hopefully you can get something out of this

**Comment by PoomSmart** [comment]
@scgames83 Here's the new IPA to test.

https://github.com/qnblackcat/uYouPlus/actions/runs/3012095245

**Comment by scgames83** [comment]
@PoomSmart Still crashing for me. I even tried other modified YouTube IPAs and they're crashing too. I got no clue if it has something to do with a line of code from Google or something on my device (I am running the iOS 16 developer beta after all, even though it worked fine beforehand). I still appreciate the time you've taken to look into this.

**Comment by slaynsubaki** [comment]
@scgames83 so far I haven't had crashes after enabling fake YouTube version. The rest I leave it as default. 

BTW, I'm using CercubePlus ipa instead of uYouPlus

**Comment by scgames83** [comment]
@slaynsubaki Even that's not working for me. Must be something on my end that's causing it. I'll upload the new crash log  if anyone wants to take a look at it. I'm honestly just so stumped at the moment. 
[YouTube-2022-09-08-002950.ips.zip](https://github.com/qnblackcat/uYouPlus/files/9523587/YouTube-2022-09-08-002950.ips.zip)

**Comment by PoomSmart** [comment]
@scgames83 Would you be able to connect your phone with your macOS laptop, open Console, select your phone, filter the logs with "YouTube" text with category "Process", start the logging and see what is logged during the app crash?

<img width="822" alt="image" src="https://user-images.githubusercontent.com/3608783/189037400-fdbde54a-1edc-4b4d-80a0-037fbf43c526.png">

**Comment by scgames83** [comment]
@PoomSmart I got 2 different process logs that could better explain what's happening (Mostly the second one but I know I should still send the first).
<img width="793" alt="Screenshot 2022-09-08 at 1 00 26 AM" src="https://user-images.githubusercontent.com/32241975/189038526-2192c130-547f-432d-8936-bc5b3c463be7.png">
<img width="793" alt="Screenshot 2022-09-08 at 1 00 48 AM" src="https://user-images.githubusercontent.com/32241975/189038538-8e21f539-276f-4ad0-8241-4fb1ef03eaaa.png">

**Comment by PoomSmart** [comment]
Thanks! `YTPlaybackStrippedWatchController` is very interesting here.

**Comment by PoomSmart** [comment]
@scgames83 And this one should work ;)
https://github.com/qnblackcat/uYouPlus/actions/runs/3012674125

**Comment by scgames83** [comment]
@PoomSmart You did it :)
Thank you for all the help, even if it took a while to get here. I really appreciate it.

**Comment by TheLidlMan** [comment]
Just stared for me 12 hours ago 😩

**Comment by qnblackcat** [comment]
Fixed in [v17.35.3-2.1](https://github.com/qnblackcat/uYouPlus/releases/tag/v17.35.3-2.1)

**Comment by xXRealXxx** [comment]
The app crashes for me whenever I try to I try to play any video by clicking on it. Strangely, it can play on the feed though for some reason. Reinstalling uYou+ and AltStore doesn't fix this issue. Using the app without a Google account also doesn't help. Disabling Return Youtube Dislike doesn't help. Enable fake app version in PiP settings doesn't help either. Crashes on stock settings too.
iPhone 8 Plus on latest iOS (16.7.7) with latest uYou+ installed from the website

**Comment by aaronliu0130** [comment]
Personally, I've gone over to https://github.com/arichornlover/uYouEnhanced since qnBlackcat stopped maintaining

**Comment by xXRealXxx** [comment]
> Personally, I've gone over to https://github.com/arichornlover/uYouEnhanced since qnBlackcat nearly stopped maintaining

That crashes too the same way. Tested it on a different iPhone. A iPhone XS Max.

**Comment by aaronliu0130** [comment]
Well, I can't reproduce that. Where did you get the IPAs?

**Comment by xXRealXxx** [comment]
uyouplus.com and the direct AltStore link: https://tinyurl.com/2s4zrj2h

**Comment by xXRealXxx** [comment]
It worked fine for a while but today it stopped working for some reason

**Comment by aaronliu0130** [comment]
YouTube Reborn Plus is very different software.

**Comment by aaronliu0130** [comment]
Try disabling YouPIP per https://github.com/arichornlover/uYouEnhanced/issues/460

**Comment by xXRealXxx** [comment]
> Try disabling YouPIP per [arichornlover#460](https://github.com/arichornlover/uYouEnhanced/issues/460)

I disabled YouPIP in YouTube Reborn Plus and that didn't fix the crashing.

**Comment by xXRealXxx** [comment]
Disabling SponsorBlock also doesn't fix this.

**Comment by xXRealXxx** [comment]
[YouTube-2024-04-05-213008.zip](https://github.com/qnblackcat/uYouPlus/files/14893265/YouTube-2024-04-05-213008.zip)

**Comment by xXRealXxx** [comment]
Same thing happens on uYouPlus from uyouplus.com
And I was using uYouEnhanced

**Comment by xXRealXxx** [comment]
For some reason, disabling Sponsorblock on uYouPlus and restarting this app fixes the crashing issue. Weird.

**Comment by WestonJFord** [comment]
Same here, the app seems to crash if iSponsorblock is enabled.
